### ISSUE TITLE
local docs generation doesn't have permission to execute scripts

### ISSUE THREAD

**Issue by runspired** [ember-learn/ember-jsonapi-docs#118]
On a fresh clone, `await execa(cmd, { cwd: path, shell: true })` fails 

(note `pnpm install` is run here because I've patched this locally since `ember-data` uses pnpm and not `yarn`). The same error results in a fresh install for `yarn`.

> cthoburn@Chris-Thoburn-K50Q30D761 ember-jsonapi-docs % yarn gen --project ember-data --version 4.12.0
yarn run v1.22.19
$ node -r esm generate-local.js --project ember-data --version 4.12.0
Running 'pnpm install' in '/Users/cthoburn/github/data'
Error: Command failed with exit code 1 (EPERM): pnpm install
    at makeError (/Users/cthoburn/github/ember-jsonapi-docs/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/Users/cthoburn/github/ember-jsonapi-docs/node_modules/execa/index.js:112:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runCmd (/Users/cthoburn/github/ember-jsonapi-docs/generate-local.js:20:22)
    at async buildDocs (/Users/cthoburn/github/ember-jsonapi-docs/generate-local.js:58:3)
    at async /Users/cthoburn/github/ember-jsonapi-docs/generate-local.js:82:2

**Comment by runspired** [comment]
I improved the error output and figured out the issue is that if running the build/docs generation in this way your global node and global pnpm must match ember-data's because even with `shell: true` or `shell: 'zsh'` execa doesn't properly setup the env.
